# coding: utf-8

"""
    Maxar Content API - Catalog

    The Maxar Content Catalog API implements a STAC-compliant service for searching the Maxar content catalog.  __The STAC specification is still under development.  When version 1.0 of the STAC specification is released the Content Catalog API will be updated to reflect any changes, some of which will not be backward compatible with this current version.__  For information on STAC see [stacspec.org](https://stacspec.org)   # noqa: E501

    OpenAPI spec version: 0.9
    Contact: DL-Content-Catalog@maxar.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Healthcheck(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'overall': 'str',
        'database': 'str',
        'links': 'object'
    }

    attribute_map = {
        'overall': 'overall',
        'database': 'database',
        'links': '_links'
    }

    def __init__(self, overall=None, database=None, links=None):  # noqa: E501
        """Healthcheck - a model defined in Swagger"""  # noqa: E501
        self._overall = None
        self._database = None
        self._links = None
        self.discriminator = None
        if overall is not None:
            self.overall = overall
        if database is not None:
            self.database = database
        if links is not None:
            self.links = links

    @property
    def overall(self):
        """Gets the overall of this Healthcheck.  # noqa: E501


        :return: The overall of this Healthcheck.  # noqa: E501
        :rtype: str
        """
        return self._overall

    @overall.setter
    def overall(self, overall):
        """Sets the overall of this Healthcheck.


        :param overall: The overall of this Healthcheck.  # noqa: E501
        :type: str
        """

        self._overall = overall

    @property
    def database(self):
        """Gets the database of this Healthcheck.  # noqa: E501


        :return: The database of this Healthcheck.  # noqa: E501
        :rtype: str
        """
        return self._database

    @database.setter
    def database(self, database):
        """Sets the database of this Healthcheck.


        :param database: The database of this Healthcheck.  # noqa: E501
        :type: str
        """

        self._database = database

    @property
    def links(self):
        """Gets the links of this Healthcheck.  # noqa: E501


        :return: The links of this Healthcheck.  # noqa: E501
        :rtype: object
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Healthcheck.


        :param links: The links of this Healthcheck.  # noqa: E501
        :type: object
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Healthcheck, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Healthcheck):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
