# coding: utf-8

"""
    Maxar MGP Discovery API

    The Maxar MGP Discovery API implements a STAC-compliant service for searching the Maxar content catalog.  __The STAC specification is still under development.  When version 1.0 of the STAC specification is released the Discovery API will be updated to reflect any changes, some of which may not be backward compatible with this current version.__  For information on STAC see [stacspec.org](https://stacspec.org)   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import maxarcat_client
from maxarcat_client.api.stac_api import STACApi  # noqa: E501
from maxarcat_client.rest import ApiException


class TestSTACApi(unittest.TestCase):
    """STACApi unit test stubs"""

    def setUp(self):
        self.api = STACApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_conformance(self):
        """Test case for get_conformance

        Information about specifications that this API conforms to  # noqa: E501
        """
        pass

    def test_get_healthcheck(self):
        """Test case for get_healthcheck

        Service healthcheck  # noqa: E501
        """
        pass

    def test_get_queryables_stac(self):
        """Test case for get_queryables_stac

        Queryables for Discovery API  # noqa: E501
        """
        pass

    def test_get_root(self):
        """Test case for get_root

        Return the root catalog or collection.  # noqa: E501
        """
        pass

    def test_get_search_stac(self):
        """Test case for get_search_stac

        Search STAC items with filtering.  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        Service status  # noqa: E501
        """
        pass

    def test_post_search_stac(self):
        """Test case for post_search_stac

        Search STAC items with filtering.  # noqa: E501
        """
        pass

    def test_validate_stac_object(self):
        """Test case for validate_stac_object

        Validate a STAC object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
